const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/auth',      require('./routes/auth'));
app.use('/api/cours',     require('./routes/cours'));
app.use('/api/entretien', require('./routes/entretien'));
app.use('/api/agent',     require('./routes/agent'));
app.get('/', (req, res) => res.json({ message: 'EduXpert API v2 running' }));
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server on port ${PORT}`));
